import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Front-End Interview Questions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <strong>F</strong>ront-<strong>E</strong>nd <strong>I</strong>nterview{" "}
          <strong>Q</strong>uestions
        </h1>

        <p className={styles.description}>
          Open Source front-end flash cards
        </p>

        <div className={styles.grid}>
          <a href="/javascript" className={styles.card}>
            <h2>JavaScript &rarr;</h2>
            <p>JavaScript interview questions</p>
          </a>
          <a href="/typescript" className={styles.card}>
            <h2>TypeScript &rarr;</h2>
            <p>TypeScript interview questions</p>
          </a>
          <a href="/react" className={styles.card}>
            <h2>React &rarr;</h2>
            <p>React interview questions</p>
          </a>
          <a href="/css-html" className={styles.card}>
            <h2>CSS & HTML &rarr;</h2>
            <p>CSS and HTML interview questions</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
